#!/bin/bash
# USB兼容性深度修复测试脚本
# 用于验证ZYNQ7010 USB CDC-ACM设备枚举

echo "=========================================="
echo "USB兼容性深度修复测试"  
echo "目标: 解决设备描述符请求失败问题"
echo "=========================================="

echo "修复摘要:"
echo "1. 设备类改为标准CDC (0x02)"
echo "2. VID/PID改为兼容的Cypress (0x04B4:0x0008)" 
echo "3. 功耗降低到100mA (总线供电)"
echo "4. 简化协议配置"
echo "5. 增强调试输出"
echo ""

echo "预期调试输出:"
echo "- ZYNQ7010 USB CDC-ACM Virtual Serial Port - Deep Compatibility Mode"
echo "- Device Class: CDC (0x02) - Maximum Compatibility"
echo "- Vendor ID: 0x04B4 (Cypress), Product ID: 0x0008"
echo "- USB Setup: Type=0x80, Req=0x06... (设备描述符请求)"
echo "- Device Descriptor Request: BufLen=..., DescSize=18"
echo "- Device Descriptor sent successfully: 18 bytes"
echo ""

echo "测试步骤:"
echo "1. 编译并烧录固件到ZYNQ7010"
echo "2. 连接USB线缆"
echo "3. 监控UART调试输出"
echo "4. 检查Windows设备管理器"
echo ""

echo "成功标志:"
echo "- 设备管理器显示CDC设备而非'未知设备'"
echo "- 调试输出显示设备描述符成功发送"
echo "- 设备枚举完成消息"
echo ""

echo "如果仍然失败的排查步骤:"
echo "1. 检查USB线缆和连接"
echo "2. 验证ZYNQ7010供电和时钟"
echo "3. 确认USB3320C PHY配置"
echo "4. 检查Windows USB驱动程序"
echo "5. 尝试不同的主机(Linux/Mac)"
echo ""

echo "调试命令参考:"
echo "# 在Windows查看USB设备:"
echo "# 设备管理器 -> 查看 -> 显示隐藏的设备"
echo "# 或使用 usbview.exe 工具"
echo ""
echo "# 在Linux查看USB设备:"
echo "# dmesg | tail -20"
echo "# lsusb -v | grep -A20 04b4:0008"
echo ""

echo "=========================================="
echo "测试开始时间: $(date)"
echo "=========================================="
